### ISSUE TITLE
Make schema validation mandatory

### ISSUE THREAD

**Issue by trygve-lie** [podium-lib/labs#13]
I like that one can add schemas for validation and sanitizing of parameters to the content and fallback routes (https://github.com/podium-lib/labs/pull/11).

Though; could be make this mandatory? I think we can do this by adding a default schema, which is empty, for each route and if the developer want to use parameters on one of these routes she must define a schema with the parameters which should be allowed.

I have 3 reasons for making this mandatory:

 * Validation and sanitizing input is a good thing in general. Its something everyone should do, but something a lot is sloppy on doing.
 * One thing we hear developers struggle with when it comes to podets is that they find it hard to know which params can be passed in, what type and which are required and not. If we make defining schemas for this mandatory we can use the schemas not just for validation but also to expose information about what the podlets can take of input. We could then ex have separate routes using the schemas to print what each route can take of params etc.
 * Further down the line we would also like to extend the podium manifest so a podlet can tell a layout which params it can take and must have to work. Today that is very loose, but if can require this through schemas it would make it a lot easier for us to making it safer to pass parameters from the layout to the podlets automatically.

The downside of this is that defining the schemas can be a bit unusual for developers but I think the wins out weights this downside.

**Comment by digitalsadhu** [comment]
Fixed in #18
